In [1]:
from sklearn import svm, metrics
import settings
from helper import *
from emoji import Emoji, EmojiOutputFormat
import numpy as np
import random
from sklearn import metrics, decomposition

2022-12-12 17:34:30,817 [INFO]: Logging is now in charge of logging.


[INFO] Settings: Start initializing.
[INFO] Settings: Folder already exists in Dir /home/loe/Projects/STATS-304/GP/.config/, skipping creation.
[INFO] Settings: Reading from file.
[INFO] Settings: Performing integrity check.
[INFO] Settings: New config file generated.
[INFO] Settings: Apply environment variable.
[INFO] Settings: Folder already exists in Dir /home/loe/Projects/STATS-304/GP/.config/, skipping creation.
[INFO] Settings: Folder already exists in Dir /home/loe/Projects/STATS-304/GP/.data, skipping creation.
[INFO] Settings: ROOT_DIR - /home/loe/Projects/STATS-304/GP
[INFO] Settings: CONFIG_DIR - /home/loe/Projects/STATS-304/GP/.config/
[INFO] Settings: DATA_DIR - /home/loe/Projects/STATS-304/GP/.data
[INFO] Settings: LOG_LEVEL - DEBUG
[INFO] Settings: Finish initializing.


In [2]:
# Change how you want the data loo like
# X,y = RGB_and_PCA_load()
# X,y = grayscale_and_resize_load()
# X,y = grayscale_enlarge_and_shrink()
# X,y = RGBA_enlarge_and_shrink()
# X,y = grayscale_and_resize_load_small()
X,y = RGBA_enlarge_and_shrink_large()

/home/loe/.local/lib/python3.10/site-packages/PIL/Image.py:979: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(


In [17]:
# random.shuffle(iris) # This thing breaks list. I do not know why.
X_new = X.copy()
y_new = y.copy()
sequence = []
random.seed(114)
while len(sequence) != X.shape[0]:
    i = random.randint(0,X.shape[0]-1)
    if i not in sequence:
        sequence.append(i)
#print(sequence)
for i_ind, i_val in enumerate(X):
    X_new[sequence[i_ind]] = i_val
    y_new[sequence[i_ind]] = y[i_ind]
X = X_new.copy()
y = y_new.copy()

In [18]:
# Visualize input data
print(f"X shape: {X.shape}")
print(f"y shape: {y.shape}")


X shape: (6226, 1296)
y shape: (6226,)


In [19]:
portion = 0.3
num_of_train = int(X.shape[0]*(1-portion))
X_train = X[:num_of_train]
y_train = y[:num_of_train]
X_test = X[num_of_train:]
y_test = y[num_of_train:]

In [20]:
model = svm.SVC(cache_size=2000)
model.fit(X_train, y_train)

SVC(cache_size=2000)

In [21]:
y_pred = model.predict(X_test)


In [22]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", metrics.confusion_matrix(y_test,y_pred))

Accuracy: 0.9014989293361885
Confusion Matrix:
 [[693  25  41]
 [ 27 542  24]
 [ 30  37 449]]
